#!/bin/bash
#命令安装器
SCRIPT_VERSION="1.0.0"
SCRIPT_NAME="lbsh_installer"
LBSH_HOME="~/.lbsh"

INSTALL_SUPPORT_ARR=("lssh","tester")
INSTALL_SUPPORT_APP_HOME_ARR=("./lssh")

BIN_HOME="./__install_test/bin"

function msg() {
    if [ "$1" == "log" ]; then
        if [ "$2" == "error" ]; then
            echo -e "[${SCRIPT_NAME}] $(date '+%Y-%m-%d %H:%M:%S') \e[31mERROR\e[0m: $3" 1>&2
        else
            echo "[${SCRIPT_NAME}] $(date '+%Y-%m-%d %H:%M:%S')  INFO: $2"
        fi
    else
        if [ "$1" == "error" ]; then
            echo -e "\e[31mERROR:\e[0m $2"
        else
            echo "$*"
        fi
    fi
}

function isContains() {
    narr=($1)
    [[ ${narr[@]/$2/} == ${narr[@]} ]]
    echo $?
}

function isExistDir() {
    if [ $1 != "" ]; then
        if [ ! -d "$1" ]; then
            mkdir $1
        fi
    fi
}

function installerForLssh() {
    # isExistDir $LBSH_HOME
    # TODO test to get current user home absolute,cause cant use ~/
    echo $username
}

if [ "$1" == "" ] || [ "$1" == "-h" ]; then
    msg "   Usage: $0 [options] [command]"
    msg " "
    msg "   Commands: "
    msg "          i,install        install [$INSTALL_SUPPORT_ARR] for your system"
    msg "          u,unstall        unstall"
    msg " "
    msg "   Options: "
    msg "          <default>,-h     Output usage information"
    msg "          -v               Verbose mode"
elif [ "$1" == "i" ]; then
    if [ "$2" == "" ]; then
        msg "Unable to install empty, plase try to install [$INSTALL_SUPPORT_ARR]."
    elif [ "$2" == "lssh" ]; then
        echo 2
        installerForLssh
    else
        msg "$2 is not supported for installation, plase try to install [$INSTALL_SUPPORT_ARR]."
    fi
elif [ "$1" == "-v" ]; then
    msg "${SCRIPT_NAME} version: v${SCRIPT_VERSION}."
else
    msg "$1 is not supported by ${SCRIPT_NAME}."
fi
