#!/bin/bash
function cecho() {
    if [ "$1" == "red" ]; then
        echo -e "\033[31m$2\033[0m"
    elif [ "$1" == "yellow" ]; then
        echo -e "\033[33m$2\033[0m"
    elif [ "$1" == "green" ]; then
        echo -e "\033[32m$2\033[0m"
    fi
}

function banner() {
    cecho red ""
    cecho red ""
    cecho red " ██▓     █    ██  ▒█████   ▄▄▄▄    ▒█████       ██████  ██░ ██ ▓█████  ██▓     ██▓    "
    cecho red "▓██▒     ██  ▓██▒▒██▒  ██▒▓█████▄ ▒██▒  ██▒   ▒██    ▒ ▓██░ ██▒▓█   ▀ ▓██▒    ▓██▒    "
    cecho red "▒██░    ▓██  ▒██░▒██░  ██▒▒██▒ ▄██▒██░  ██▒   ░ ▓██▄   ▒██▀▀██░▒███   ▒██░    ▒██░    "
    cecho red "▒██░    ▓▓█  ░██░▒██   ██░▒██░█▀  ▒██   ██░     ▒   ██▒░▓█ ░██ ▒▓█  ▄ ▒██░    ▒██░    "
    cecho red "░██████▒▒▒█████▓ ░ ████▓▒░░▓█  ▀█▓░ ████▓▒░   ▒██████▒▒░▓█▒░██▓░▒████▒░██████▒░██████▒"
    cecho red "░ ▒░▓  ░░▒▓▒ ▒ ▒ ░ ▒░▒░▒░ ░▒▓███▀▒░ ▒░▒░▒░    ▒ ▒▓▒ ▒ ░ ▒ ░░▒░▒░░ ▒░ ░░ ▒░▓  ░░ ▒░▓  ░"
    cecho red "░ ░ ▒  ░░░▒░ ░ ░   ░ ▒ ▒░ ▒░▒   ░   ░ ▒ ▒░    ░ ░▒  ░ ░ ▒ ░▒░ ░ ░ ░  ░░ ░ ▒  ░░ ░ ▒  ░"
    cecho red "  ░ ░    ░░░ ░ ░ ░ ░ ░ ▒   ░    ░ ░ ░ ░ ▒     ░  ░  ░   ░  ░░ ░   ░     ░ ░     ░ ░   "
    cecho red "    ░  ░   ░         ░ ░   ░          ░ ░           ░   ░  ░  ░   ░  ░    ░  ░    ░  ░"
    cecho red "                                ░                                                     "
    cecho red ""
}

function pause() {
  sed -n q </dev/tty
}

function cmd_exist_or_exist(){
    command -v foo >/dev/null 2>&1 || { 
    echo >&2 "I require foo but it's not installed.  Aborting.";
    exit 1; 
}
}


function welcome() {
    clear
    banner
}

function env_check(){

}

function main() {
    welcome
    env_check
}

main
