#!/bin/bash
#命令安装器
SCRIPT_VERSION="1.0.0"
SCRIPT_NAME="lbsh_installer"

function msg(){
    if [ "$1" == "err" ]
    then
        echo -e "$(date '+%Y-%m-%d %H:%M:%S') \e[31m${SCRIPT_NAME} ERROR\e[0m: $2" 1>&2
    elif [ "$1" == "info" ]
    then
        echo "$(date '+%Y-%m-%d %H:%M:%S') ${SCRIPT_NAME}: $*"
    else
        echo "$*"
    fi
}


if [ "$1" == "" ] || [ "$1" == "-h" ]
then
    msg "   Usage: $0 [options] [command]"
    msg " "
    msg "   Commands: "
    msg "          lssh             Install global command lssh"
    msg " "
    msg "   Options: "
    msg "          <default>,-h     Output usage information"
    msg "          -v               Verbose mode"
elif [ "$1" == "lssh" ]
then
    msg "lssh"
elif [ "$1" == "-v" ]
then
    msg "${SCRIPT_NAME} version: v${SCRIPT_VERSION}"
else
    msg ERROR "$1 is not supported by ${SCRIPT_NAME}"
fi