#!/bin/bash
# ssh增强 用于保存会话快速登录
# 依赖列表
SCRIPT_VERSION="1.0.0"
SCRIPT_NAME="lb-ssh"

function msg(){
    if [ "$1" == "log" ]
    then
        if [ "$2" == "error" ]
        then
            echo -e "$(date '+%Y-%m-%d %H:%M:%S') \e[31m${SCRIPT_NAME} ERROR\e[0m: $3" 1>&2
        else
        then
            echo "$(date '+%Y-%m-%d %H:%M:%S') ${SCRIPT_NAME}: $*"
        fi
    else
    then
        if [ "$1" == "error" ]
        then
            echo -e "\e[31mERROR\e $*"
        else
        then
            echo "$*"
        fi
    fi
}


if [ "$1" == "" ] || [ "$1" == "r" ]
then
    msg "run"
elif [ "$1" == "ls" ]
then
    msg "ls"
elif [ "$1" == "-h" ]
then
    msg "   Usage: $0 [options] [command]"
    msg "          $0 use name or ip or id"
    msg " "
    msg "   Repositories: [sshpass]"
    msg " "
    msg "   Commands: "
    msg "          <default>,r      Connecting a ssh session"
    msg "          ls               Output all configured ssh sessions"
    msg " "
    msg "   Options: "
    msg "          -h               Output usage information"
    msg "          -v               Verbose mode"
elif [ "$1" == "-v" ]
then
    msg "${SCRIPT_NAME} version: v${SCRIPT_VERSION}"
else
    msg "$1 is not supported by ${SCRIPT_NAME}"
fi

# sshpass -p '123456' ssh shtf@192.168.1.46
