#!/bin/bash
SCRIPT_VERSION="1.0.0"
SCRIPT_NAME="lb-ssh"

function msg(){
    if [ "$1" == "err" ]
    then
        echo -e "$(date '+%Y-%m-%d %H:%M:%S') \e[31m${SCRIPT_NAME} ERROR\e[0m: $2" 1>&2
    elif [ "$1" == "info" ]
    then
        echo "$(date '+%Y-%m-%d %H:%M:%S') ${SCRIPT_NAME}: $*"
    else
        echo "$*"
    fi
}


if [ "$1" == "" ] || [ "$1" == "r" ]
then
    msg "run"
elif [ "$1" == "ls" ]
then
    msg "ls"
elif [ "$1" == "-h" ]
then
    msg "   Usage: $0 [options] [command]"
    msg "          $0 use name or ip or id"
    msg " "
    msg "   Commands: "
    msg "          <default>,r      Connecting a ssh session"
    msg "          ls               Output all configured ssh sessions"
    msg " "
    msg "   Options: "
    msg "          -h     Output usage information"
    msg "          -v,-verison      Verbose mode"
elif [ "$1" == "-v" ]
then
    msg "${SCRIPT_NAME} version: v${SCRIPT_VERSION}"
fi

# sshpass -p '123456' ssh shtf@192.168.1.46
