#!/bin/bash
pid=$(ps -ef | grep todesk | grep -v grep | awk '{print $2}')
[[ -n "${pid}" ]] && kill -9 ${pid}
case "${1}" in
    close)
        echo close ${pid}
        ;;
    start)
        todesk &
        ;;
    *)
    echo no support
    ;;
esac
